---
abstract: '...'
author:
  - 'Mons Anderson, C<< <mons@cpan.org> >>'
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  lib::abs: 0.90
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-RW
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  AnyEvent::RW:
    file: lib/AnyEvent/RW.pm
    version: 0.01
  AnyEvent::RW::RQ:
    file: lib/AnyEvent/RW/RQ.pm
  AnyEvent::RW::TLS:
    file: lib/AnyEvent/RW/TLS.pm
  AnyEvent::RW::TLSRQ:
    file: lib/AnyEvent/RW/TLSRQ.pm
requires:
  AnyEvent: 5
  common::sense: 2
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
